# Federated Agent daemonset...

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: federated-agent
  namespace: spire
  labels:
    app: federated-agent
    realm: spire-control-plane
spec:
  selector:
    matchLabels:
      app: federated-agent
  template:
    metadata:
      namespace: spire
      labels:
        app: federated-agent
        realm: spire-control-plane
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: federated-agent
      initContainers:
        - name: init
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/lqhl/wait-for-it
          image: gcr.io/spiffe-io/wait-for-it
          args: ["-t", "30", "federated-server:8081"]
      containers:
        - name: federated-agent
          image: ghcr.io/spiffe/spire-agent:1.6.1
          args: ["-config", "/run/spire/config/agent.conf"]
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-agent-bootstrap
              mountPath: /run/spire/bootstrap
              readOnly: true
            - name: federated-agent-socket
              mountPath: /run/spire/sockets
              readOnly: false
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: spire-config
          configMap:
            name: federated-agent-conf
        - name: spire-agent-bootstrap
          configMap:
            name: federated-agent-bootstrap-cert
          # Share the UDS socket to enable nested downstream nodes (or whatever) to attest to this agent.
        - name: federated-agent-socket
          hostPath:
            path: /run/spire/sockets/federated
            type: DirectoryOrCreate
