# Root Server StatefulSet and Service...

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: root-server
  namespace: spire
  labels:
    app: root-server
    realm: spire-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root-server
  serviceName: root-server
  template:
    metadata:
      namespace: spire
      labels:
        app: root-server
        realm: spire-control-plane
    spec:
      serviceAccountName: root-server
      containers:
        - name: root-server
          image: ghcr.io/spiffe/spire-server:1.6.1
          args: ["-config", "/run/spire/config/server.conf"]
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
            - name: spire-upstream-authority-cert
              mountPath: /run/spire/ua-cert
              readOnly: true
            - name: spire-upstream-authority-key
              mountPath: /run/spire/ua-key
              readOnly: true
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 6000
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: spire-config
          configMap:
            name: root-server-conf
        - name: spire-upstream-authority-cert
          configMap:
            name: root-server-upstream-authority
        - name: spire-upstream-authority-key
          secret:
            secretName: root-server-upstream-authority
  volumeClaimTemplates:
    - metadata:
        name: spire-data
        namespace: spire
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: root-server
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: root-server
