# Root Agent daemonset...

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: root-agent
  namespace: spire
  labels:
    app: root-agent
    realm: spire-control-plane
spec:
  selector:
    matchLabels:
      app: root-agent
  template:
    metadata:
      namespace: spire
      labels:
        app: root-agent
        realm: spire-control-plane
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: root-agent
      initContainers:
        - name: init
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/lqhl/wait-for-it
          image: gcr.io/spiffe-io/wait-for-it
          args: ["-t", "30", "root-server:8081"]
      containers:
        - name: root-agent
          image: gcr.io/spiffe-io/spire-agent:1.5.3
          args: ["-config", "/run/spire/config/agent.conf"]
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-agent-bootstrap
              mountPath: /run/spire/bootstrap
              readOnly: true
            - name: root-agent-socket
              mountPath: /run/spire/sockets
              readOnly: false
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: spire-config
          configMap:
            name: root-agent-conf
        - name: spire-agent-bootstrap
          configMap:
            name: root-agent-bootstrap-cert
          # Share the UDS socket to enable nested downstream nodes (or whatever) to attest to this agent.
        - name: root-agent-socket
          hostPath:
            path: /run/spire/sockets/root
            type: DirectoryOrCreate
